# =================================================================
# PROFILES: DEV
# ==================================================================
server:
  port: 8080
  servlet:
    session:
      context-path: /dev
      timeout: 3000m

spring:
  config.activate.on-profile: local
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/book_mall?characterEncoding=UTF-8&serverTimezone=UTC
    username: bookDb
    password: tkdlemqnr@1
